sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10.15.3"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphicsmagick
  - sudo apt-get install -y ghostscript
  - npm i
  - npm i -g validate-npm-package-name
script:
  - npm run test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
