sudo: true
language: node_js
notifications:
  email: false
node_js:
  - "10.15.3"
cache:
  npm: true,
  directories:
    - "node_modules"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphicsmagick
  - sudo apt-get install -y ghostscript
before_script:
  - npm prune
script:
  - npm run test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
